language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing to install"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # just to print out the docker version used
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend jeffron/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"  --password-stdin
  - docker push jeffron/udagram-frontend:v1